In [1]:
import numpy as np

In [2]:
arr=np.array([23,45,60])

In [3]:
arr


array([23, 45, 60])

In [4]:
w1,w2,w3=0.3,0.2,0.5

In [5]:
wt=np.array([w1,w2,w3])

In [6]:
wt

array([0.3, 0.2, 0.5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(wt)

numpy.ndarray

In [9]:
wt[0]

0.3

In [10]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [11]:
arr[2]

60

In [12]:
np.dot(arr,wt)

45.9

In [13]:
(arr*wt).sum()

45.9

In [14]:
arr*wt

array([ 6.9,  9. , 30. ])

In [15]:
wt.sim()

AttributeError: 'numpy.ndarray' object has no attribute 'sim'

In [16]:
wt.sum()

1.0

In [19]:
ar1=list(range(100000))
ar2=list(range(100000, 200000))
var1_np=np.array(ar1)
var2_np=np.array(ar2)

In [21]:
%%time
result = 0
for x1, x2 in zip(ar1, ar2):
    result += x1*x2
result

CPU times: total: 46.9 ms
Wall time: 47 ms


833323333350000

In [22]:
%%time
np.dot(var1_np,var2_np)

CPU times: total: 0 ns
Wall time: 32 ms


893678192

In [23]:
roshan.commit

NameError: name 'roshan' is not defined

In [24]:
import roshan

ModuleNotFoundError: No module named 'roshan'